version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: kpt-db
    environment:
      POSTGRES_DB: kpt_incubation
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d kpt_incubation"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: kpt-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/kpt_incubation
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      JWT_SECRET: your-secret-key-here
      JWT_EXPIRATION: 86400000
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
      - maven-repo:/root/.m2

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: kpt-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:8080/api
    depends_on:
      - backend

volumes:
  postgres_data:
  maven-repo:
